import React from "react";
import Head from "next/head";
import Header from "../components/header";
import Mint from "../components/mint";
import Nav from "../components/nav";

import { ethers } from "ethers";

export default class Home extends React.Component {
  constructor(props) {
    super(props);
  }

  state = {
    signer: null,
  };

  async connectWallet() {
    console.log("trying to connect to wallet.");
    const walletProvider = new ethers.providers.Web3Provider(window.ethereum);
    await walletProvider.send("eth_requestAccounts", []);
    this.setState((prevState) => ({ signer: walletProvider.getSigner() }));
  }

  render() {
    return (
      <div class="bg-blue-300 min-h-screen">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Nav></Nav>

        <div class="grid md:items-center lg:grid-cols-2">
          <Header />
          <Mint walletConnect={() => this.connectWallet()} />
        </div>
        {/* 
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer> */}
      </div>
    );
  }
}
